/*
	RingVaders - Constants Module
	All game constants and configuration values
*/

# Screen and rendering
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 700
BASE_W = 600
BASE_H = 700
FPS = 60
PI = 3.14159265358979

# Game State Constants
STATE_MENU = 0
STATE_PLAYING = 1
STATE_PAUSED = 2
STATE_GAMEOVER = 3
STATE_WAVE_ANNOUNCE = 4
STATE_PLAYER_DEATH = 5
STATE_ACHIEVEMENTS = 6

# Difficulty Constants
DIFF_EASY = 0
DIFF_NORMAL = 1
DIFF_HARD = 2

# Entity limits
MAX_BULLETS = 50
MAX_ENEMY_BULLETS = 100
MAX_ENEMIES = 55
MAX_PARTICLES = 300
MAX_POWERUPS = 20
MAX_SHIELDS = 100
MAX_STARS = 100
MAX_SCORE_POPUPS = 20
MAX_BULLET_TRAILS = 150

# Powerup types
POWERUP_SHIELD = 0
POWERUP_RAPID = 1
POWERUP_MULTI = 2
POWERUP_SPREAD = 3
POWERUP_LIFE = 4

# Enemy types (visual styles)
ENEMY_CRAB = 0
ENEMY_SQUID = 1
ENEMY_OCTOPUS = 2
ENEMY_ARMORED = 3
ENEMY_SPEEDER = 4

# Sound Constants
SOUND_SHOOT = 1
SOUND_ENEMY_HIT = 2
SOUND_UFO_HIT = 3
SOUND_PLAYER_HIT = 4
SOUND_POWERUP = 5
SOUND_WAVE_CLEAR = 6
SOUND_1UP = 7
SOUND_UFO_SPAWN = 8

# Audio settings
SAMPLE_RATE = 44100

# Music type constants
MUSIC_NONE = 0
MUSIC_MENU = 1
MUSIC_MAIN = 2
MUSIC_BOSS = 3

# Save file names (paths resolved by getSaveDir())
HIGH_SCORE_FILE = "highscore.dat"
ACHIEVEMENTS_FILE = "achievements.dat"

# Save directory
SAVE_DIR = NULL